/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 皮肤分析结果契约 —— 三端共用 + 千问VL 结构化输出约束的单一真相源。分类体系(16型四维度)见 docs/adr/0006。
 */
export interface SkinReport {
  /**
   * 16型肌肤四维度,每维度自带判定值 + 独立置信度(详见 docs/adr/0006)
   */
  skinAxes: {
    /**
     * 油脂分泌
     */
    oilDry: {
      /**
       * O 油 / D 干
       */
      value: "O" | "D";
      /**
       * 该维度置信度 0-1;偏低时前端标「参考」
       */
      confidence: number;
    };
    /**
     * 敏感程度(单张照片判定较不稳,通常低置信,前端以「参考」呈现)
     */
    sensitivity: {
      /**
       * S 敏感 / R 耐受
       */
      value: "S" | "R";
      /**
       * 该维度置信度 0-1;偏低时前端标「参考」
       */
      confidence: number;
    };
    /**
     * 痘痘情况
     */
    acne: {
      /**
       * A 有痘 / F 无痘
       */
      value: "A" | "F";
      /**
       * 该维度置信度 0-1;偏低时前端标「参考」
       */
      confidence: number;
    };
    /**
     * 色沉情况
     */
    pigment: {
      /**
       * P 有色沉 / N 无色沉
       */
      value: "P" | "N";
      /**
       * 该维度置信度 0-1;偏低时前端标「参考」
       */
      confidence: number;
    };
  };
  /**
   * 四维派生码,如 O-S-F-P(后端按 skinAxes 拼出,两端直接渲染,不各自查表)
   */
  skinTypeCode: string;
  /**
   * 四维派生中文名,如 油敏色皮(后端按 16 型映射派生)
   */
  skinTypeName: string;
  /**
   * 分区评估(部位问题点,与 16 型整脸分型正交互补)
   */
  zones: {
    /**
     * 分区名,如 T区 / 脸颊
     */
    area: string;
    /**
     * 该区问题点
     */
    issues: string[];
    /**
     * 分区评分 0-10,供卡片可视化
     */
    score: number;
  }[];
  /**
   * 护肤建议(按判定型号取该型护理思路,仅到成分/品类层,不含具体品牌/品名)
   */
  suggestions: string[];
  /**
   * 免责声明标准文案(收敛到结果页一处展示,详见 docs/adr/0008):本结果由 AI 生成,仅供护肤参考,不构成医疗建议,严重皮肤问题请就医。
   */
  disclaimer: string;
}
